/**
 * Layer 13 — Skills: Generator
 *
 * Generates new skill files from a description.
 * The user describes what the skill should do, and the generator
 * creates a properly structured skill file.
 *
 * Usage: /skill-create "Name" "Description of what it does"
 */

import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import type { Skill, SkillContext, SkillResult } from './loader.js';

/**
 * Generate a skill file from a name and description.
 */
export function generateSkillSource(
  name: string,
  description: string,
  triggers: string[],
  category: string,
): string {
  const varName = name.replace(/[^a-zA-Z0-9]/g, '') + 'Skill';
  const triggerLines = triggers.map((t) => {
    if (t.startsWith('/')) {
      return `    { type: 'command', command: '${t.slice(1)}' },`;
    }
    return `    { type: 'keyword', keywords: ['${t}'] },`;
  });

  return `/**
 * Skill: ${name}
 *
 * ${description}
 *
 * Generated by PCC Skill Generator
 */

import type { Skill, SkillContext, SkillResult } from '../loader.js';

export const ${varName}: Skill = {
  name: '${name.toLowerCase().replace(/\s+/g, '-')}',
  description: '${description.replace(/'/g, "\\'")}',
  category: '${category}',
  triggers: [
${triggerLines.join('\n')}
  ],

  async execute(ctx: SkillContext): Promise<SkillResult> {
    const args = ctx.args.trim();

    // TODO: Implement the skill logic
    return {
      type: 'prompt',
      prompt: \`Execute the "${name}" skill with input: "\${args}"\`,
    };
  },
};
`;
}

/**
 * Save a generated skill to the external skills directory.
 */
export function saveGeneratedSkill(
  skillsDir: string,
  filename: string,
  source: string,
): string {
  if (!existsSync(skillsDir)) {
    mkdirSync(skillsDir, { recursive: true });
  }

  const filePath = join(skillsDir, filename);
  writeFileSync(filePath, source, 'utf-8');
  return filePath;
}

// ─── Skill Creator Skill ───────────────────────────────

export const skillCreatorSkill: Skill = {
  name: 'skill-create',
  description: 'Generate a new skill from a description',
  category: 'utility',
  triggers: [
    { type: 'command', command: 'skill-create' },
    { type: 'command', command: 'create-skill' },
  ],

  async execute(ctx: SkillContext): Promise<SkillResult> {
    const args = ctx.args.trim();

    if (!args) {
      return {
        type: 'error',
        message: `Usage: /skill-create "<name>" "<description>"
Example: /skill-create "deploy" "Deploy the current project to production with pre-checks"`,
      };
    }

    // Parse quoted strings
    const matches = args.match(/"([^"]+)"/g);
    if (!matches || matches.length < 2) {
      return {
        type: 'error',
        message: 'Provide name and description in quotes: /skill-create "name" "description"',
      };
    }

    const name = matches[0]!.slice(1, -1);
    const description = matches[1]!.slice(1, -1);

    return {
      type: 'prompt',
      prompt: `Generate a new PCC skill:
Name: "${name}"
Description: "${description}"

Create a TypeScript file at ~/.pcc/skills/${name.toLowerCase().replace(/\s+/g, '-')}.ts with:
1. Proper imports from the skill loader
2. A well-designed execute function that fulfills the description
3. Appropriate triggers (command trigger matching the name, plus relevant keywords)
4. Error handling and user feedback
5. Clear documentation comments

Use the Write tool to create the file. Make the skill implementation practical and complete.`,
    };
  },
};
