/**
 * Layer 5 — Context: Conversation compaction
 *
 * When the conversation approaches the context window limit,
 * older turns are summarized into a compact block.
 *
 * Strategy:
 * 1. Keep the system prompt untouched
 * 2. Keep the last N turns intact (recent context)
 * 3. Summarize everything before that into a "[Previous conversation summary]" block
 * 4. Preserve tool_use/tool_result pairing in kept turns
 *
 * The summary is generated by the model itself via a dedicated compaction prompt.
 */

import type { Message, UserMessage, AssistantMessage, ContentBlock } from '../protocol/messages.js';
import type { MiniMaxClient } from '../transport/client.js';
import { isToolUseBlock, isToolResultBlock } from '../protocol/messages.js';

// ─── Configuration ──────────────────────────────────────

export interface CompactionConfig {
  /** Number of recent turns to preserve intact. Default: 4 */
  keepRecentTurns: number;
  /** Maximum tokens for the compaction summary. Default: 2048 */
  summaryMaxTokens: number;
}

export const DEFAULT_COMPACTION_CONFIG: CompactionConfig = {
  keepRecentTurns: 6,
  summaryMaxTokens: 2048,
};

// ─── Compaction ─────────────────────────────────────────

/**
 * Compact a conversation by summarizing older turns.
 * Returns a new message array with the summary prepended.
 */
export async function compactConversation(
  messages: Message[],
  client: MiniMaxClient,
  config: CompactionConfig = DEFAULT_COMPACTION_CONFIG,
): Promise<CompactionResult> {
  // Find turn boundaries (user-assistant pairs)
  const turns = identifyTurns(messages);

  if (turns.length <= config.keepRecentTurns) {
    // Not enough turns to compact
    return { messages, wasCompacted: false, removedTurns: 0 };
  }

  // Split: older turns to summarize, recent turns to keep
  const cutIndex = turns.length - config.keepRecentTurns;
  const turnsToSummarize = turns.slice(0, cutIndex);
  const turnsToKeep = turns.slice(cutIndex);

  // Extract messages for summarization
  const messagesToSummarize: Message[] = [];
  for (const turn of turnsToSummarize) {
    messagesToSummarize.push(...turn.messages);
  }

  // Generate summary — on failure, preserve original messages instead of losing context
  let summary: string;
  try {
    summary = await generateSummary(messagesToSummarize, client, config.summaryMaxTokens);
  } catch {
    return { messages, wasCompacted: false, removedTurns: 0 };
  }

  // Build compacted message array
  const summaryMessage: UserMessage = {
    role: 'user',
    content: `[Previous conversation summary — ${turnsToSummarize.length} turns compacted]\n\n${summary}\n\n[End of summary. The conversation continues below.]`,
  };

  const summaryAck: AssistantMessage = {
    role: 'assistant',
    content: [{ type: 'text', text: 'Understood. I have the context from the previous conversation. Continuing from where we left off.' }],
  };

  // Collect kept messages
  const keptMessages: Message[] = [];
  for (const turn of turnsToKeep) {
    keptMessages.push(...turn.messages);
  }

  const compactedMessages: Message[] = [
    summaryMessage,
    summaryAck,
    ...keptMessages,
  ];

  return {
    messages: compactedMessages,
    wasCompacted: true,
    removedTurns: turnsToSummarize.length,
    summaryLength: summary.length,
  };
}

// ─── Turn Identification ────────────────────────────────

interface Turn {
  messages: Message[];
}

/**
 * Group messages into turns (user→assistant→[tool_result→assistant]*).
 */
function identifyTurns(messages: Message[]): Turn[] {
  const turns: Turn[] = [];
  let currentTurn: Message[] = [];

  for (const msg of messages) {
    if (msg.role === 'user') {
      // Check if this is a tool_result continuation
      const isToolResult = Array.isArray(msg.content) &&
        msg.content.length > 0 &&
        isToolResultBlock(msg.content[0]!);

      if (isToolResult) {
        // This is a tool result, part of the current turn
        currentTurn.push(msg);
      } else {
        // New user message = new turn
        if (currentTurn.length > 0) {
          turns.push({ messages: currentTurn });
        }
        currentTurn = [msg];
      }
    } else {
      currentTurn.push(msg);
    }
  }

  if (currentTurn.length > 0) {
    turns.push({ messages: currentTurn });
  }

  return turns;
}

// ─── Summary Generation ─────────────────────────────────

const COMPACTION_PROMPT = `Summarize the following conversation as a structured action log. Use this format:

- [TOOL: name] path/target → outcome (success/error/partial)
- [DECISION] what was decided and why
- [FINDING] what was discovered or learned
- [PENDING] unresolved issues or next steps

Rules:
- Preserve ALL file paths, tool names, error messages, and specific results
- Do NOT paraphrase code — note the file and what changed
- Do NOT include conversational filler or greetings
- Include every tool call and its outcome
- Keep under 500 words`;

async function generateSummary(
  messages: Message[],
  client: MiniMaxClient,
  maxTokens: number,
): Promise<string> {
  // Build a text representation of the messages to summarize
  const conversationText = messages.map((msg) => {
    const role = msg.role;
    let content = '';
    if (typeof msg.content === 'string') {
      content = msg.content;
    } else {
      content = msg.content.map(blockToText).join('\n');
    }
    // Truncate very long content per message
    if (content.length > 2000) {
      content = content.slice(0, 2000) + '... [truncated]';
    }
    return `[${role}]: ${content}`;
  }).join('\n\n');

  const result = await client.complete(
    [{ role: 'user', content: `${COMPACTION_PROMPT}\n\n---\n\n${conversationText}` }],
    { maxTokens },
  );

  const text = result.message.content
    .filter((b) => b.type === 'text')
    .map((b) => (b as { text: string }).text)
    .join('');

  if (!text) {
    throw new Error('Summary generation produced empty output');
  }

  return text;
}

function blockToText(block: ContentBlock): string {
  switch (block.type) {
    case 'text':
      return block.text;
    case 'tool_use':
      return `[Tool: ${block.name}(${JSON.stringify(block.input).slice(0, 200)})]`;
    case 'tool_result': {
      const content = typeof block.content === 'string'
        ? block.content
        : JSON.stringify(block.content);
      const truncated = content.length > 300
        ? content.slice(0, 300) + '...'
        : content;
      return `[Result: ${truncated}]`;
    }
    case 'thinking':
      return `[Thinking: ${block.thinking.slice(0, 200)}...]`;
    default:
      return `[${block.type}]`;
  }
}

// ─── Types ──────────────────────────────────────────────

export interface CompactionResult {
  messages: Message[];
  wasCompacted: boolean;
  removedTurns: number;
  summaryLength?: number;
}
